//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Museum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string phone_num { get; set; }
        public string email { get; set; }
        public int excursion_id { get; set; }
        public int people_amount { get; set; }
        public int totalprice { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual Excursions Excursions { get; set; }
    }
}
