//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcursionsCompany.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuseumDataEntities : DbContext
    {
        public MuseumDataEntities()
            : base("name=MuseumDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Excursions> Excursions { get; set; }
        public virtual DbSet<ExcursionTypes> ExcursionTypes { get; set; }
        public virtual DbSet<Exhibits> Exhibits { get; set; }
        public virtual DbSet<ExhibitTypes> ExhibitTypes { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
