//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcursionsCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excursions()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int id { get; set; }
        public int extype_id { get; set; }
        public System.DateTime start_datetime { get; set; }
        public int price { get; set; }
        public int guide_id { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ExcursionTypes ExcursionTypes { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
