//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcursionsCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcursionTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExcursionTypes()
        {
            this.Excursions = new HashSet<Excursions>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.TimeSpan duration { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Excursions> Excursions { get; set; }
    }
}
